describe('project', () => {
  it('should be accessible from the index page', () => {
    cy.visit('/')
      .waitForRouteChange()
      .getByText(/Matt Cannon/i)
      .click()
      .waitForRouteChange()
      .assertRoute('/matt-cannon')
  })
  it('should contain title, description, images', () => {
    cy.visit('/matt-cannon')
      .waitForRouteChange()
      .getByText(/Matt Cannon/i)
      .getByText(/04.12.2017/i)
      .getByText(/Hi! I hope you like this starter and enjoy working with it./i)
      .getByAltText(/isak-dalsfelt/i)
  })
  it('should have working previous pagination link', () => {
    cy.visit('/matt-cannon')
      .waitForRouteChange()
      .getByText(/Roman Kraft/i)
      .click()
      .waitForRouteChange()
      .assertRoute('/roman-kraft')
  })
  it('should have working next pagination link', () => {
    cy.visit('/matt-cannon')
      .waitForRouteChange()
      .getByText(/Marion Michele/i)
      .click()
      .waitForRouteChange()
      .assertRoute('/marion-michele')
  })
})
